name: AI Comment Handler

on:
  issue_comment:
    types: [created]

jobs:
  trigger_probe_chat:
    # Use the reusable workflow from your repository (replace <your-org/repo> and <ref>)
    uses: buger/probe/.github/workflows/probe.yml@main
    # Pass required inputs
    with:
      command_prefix: "/probe-chat" # Or '/ai', '/ask', etc.
      # Optionally override the default npx command if the secret isn't set
      # default_probe_chat_command: 'node path/to/custom/script.js'
    # Pass ALL secrets from this repository to the reusable workflow
    # This includes GITHUB_TOKEN, PROBE_CHAT_COMMAND (if set), ANTHROPIC_API_KEY, etc.
    secrets: inherit
