# <gh>
name: Probe chat Github Action

on:
  workflow_call:
    inputs:
      command_prefix:
        description: "The prefix required on comments to trigger the AI (e.g., /probe-chat)"
        default: "/probe"
        required: true
        type: string
      default_probe_chat_command:
        description: "The default probe-chat command if PROBE_CHAT_COMMAND secret is not set"
        required: false
        default: "npx -y @buger/probe-chat@latest"
        type: string
      # Note: The actual probe-chat command to run will prioritize the PROBE_CHAT_COMMAND secret
      # passed by the caller via "secrets: inherit", then fall back to inputs.default_probe_chat_command.

# Permissions required by the jobs within THIS reusable workflow
permissions:
  pull-requests: write # Need read for context/diff, write for posting comments
  issues: write # Need read for context, write for posting comments
  contents: read # Potentially needed by gh or probe-chat

jobs:
  # Job 1: Check trigger, process context, run AI
  process_comment:
    # Only run if the comment starts with the provided prefix
    if: startsWith(github.event.comment.body, inputs.command_prefix)
    runs-on: ubuntu-latest
    outputs:
      # These outputs are set even if the 'probe' step fails, but might not be set if 'format' fails early.
      response_body: ${{ steps.read_response.outputs.response }}
      issue_number: ${{ steps.set_issue_number.outputs.issue_number }} # Set issue number early and reliably
      # This still indicates if the AI command itself succeeded, used for potential downstream logic if needed.
      probe_succeeded: ${{ steps.probe.outcome == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install jq (if needed) and Verify gh
        run: |
          # jq is usually pre-installed on ubuntu-latest, but ensure it is present
          sudo apt-get update && sudo apt-get install -y jq --no-install-recommends
          # Verify gh is available
          gh --version

      # Set issue number early so it's available even if formatting fails later
      - name: Set Issue Number Output
        id: set_issue_number
        run: echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Determine Context and Format Input
        id: format
        env:
          # Use the GITHUB_TOKEN secret passed from the caller
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMAND_PREFIX: ${{ inputs.command_prefix }} # Make prefix available
        run: |
          # Using SHELLOPTS=extglob in env is possible but less common; setting inside script is clearer
          shopt -s extglob
          set -e # Exit on error, including syntax errors or command failures

          ISSUE_OR_PR_NUMBER=${{ github.event.issue.number }}
          RAW_COMMENT_BODY="${{ github.event.comment.body }}"

          # Extract user request (remove prefix, trim whitespace)
          USER_REQUEST_BODY="${RAW_COMMENT_BODY#${COMMAND_PREFIX}}" # Remove prefix
          USER_REQUEST_BODY="${USER_REQUEST_BODY##*( )}" # Trim leading spaces (requires extglob)
          USER_REQUEST_BODY="${USER_REQUEST_BODY%%*( )}" # Trim trailing spaces (requires extglob)
          echo "User request extracted: [${USER_REQUEST_BODY}]" # Log for debugging

          # Determine context type
          CONTEXT_TYPE="issue"
          # Check if the issue context has pull_request data associated
          # Use GITHUB_REPOSITORY env var which is more standard
          if gh api "repos/${{ github.repository }}/issues/$ISSUE_OR_PR_NUMBER" --jq '.pull_request' | grep -q 'url'; then
             CONTEXT_TYPE="pr"
          fi
          echo "Context type: $CONTEXT_TYPE"

          # --- Fetch Common Data: Comments ---
          echo "Fetching comments for $CONTEXT_TYPE #$ISSUE_OR_PR_NUMBER..."
          # Fetch comments, handling potential errors during fetch
          COMMENTS_JSON=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/issues/$ISSUE_OR_PR_NUMBER/comments --jq '.' || echo "[]") # Default to empty array on error
          COMMENTS_XML=""
          echo "$COMMENTS_JSON" | jq -c '.[] | {login: .user.login, created_at: .created_at, body: .body}' | while IFS= read -r comment_json; do
            # Ensure variables are exported for the subshell used by cat <<EOF
            export login=$(echo "$comment_json" | jq -r .login)
            export created_at=$(echo "$comment_json" | jq -r .created_at)
            export body=$(echo "$comment_json" | jq -r .body)
            # Append directly, no intermediate variable needed here
            COMMENTS_XML+=$(cat <<EOF
                  <comment><author>$login</author><timestamp>$created_at</timestamp><content>$body</content></comment>
          EOF
          ) || { echo "Error processing comment JSON: $comment_json"; exit 1; } # Add error check in loop
          done
          echo "Comments fetched."

          # --- Fetch Context-Specific Data & Build XML ---
          CONTEXT_DETAILS_XML=""
          DIFF_XML=""
          PROMPT_INSTRUCTION=""

          if [[ "$CONTEXT_TYPE" == "pr" ]]; then
            echo "Fetching PR details and diff..."
            # Fetch PR data, handle potential errors
            PR_DATA=$(gh pr view $ISSUE_OR_PR_NUMBER --json title,body --repo ${{ github.repository }} || echo '{"title": "Error fetching PR title", "body": "Error fetching PR body"}')
            PR_TITLE=$(echo "$PR_DATA" | jq -r .title)
            PR_BODY=$(echo "$PR_DATA" | jq -r .body)
            # Fetch diff, handle potential errors
            PR_DIFF=$(gh pr diff $ISSUE_OR_PR_NUMBER --repo ${{ github.repository }} 2>/dev/null || echo "<!-- Error fetching diff -->")

            CONTEXT_DETAILS_XML="<details><title>$PR_TITLE</title><body>$PR_BODY</body></details>"
            DIFF_XML="<diff>$PR_DIFF</diff>"
            PROMPT_INSTRUCTION="Based *only* on the information provided within the <github_context> XML structure (including PR details, diff, and comments), please provide a response to the <user_request>."
            echo "PR details and diff fetched."

          elif [[ "$CONTEXT_TYPE" == "issue" ]]; then
            echo "Fetching Issue details..."
             # Fetch Issue data, handle potential errors
            ISSUE_DATA=$(gh issue view $ISSUE_OR_PR_NUMBER --json title,body --repo ${{ github.repository }} || echo '{"title": "Error fetching Issue title", "body": "Error fetching Issue body"}')
            ISSUE_TITLE=$(echo "$ISSUE_DATA" | jq -r .title)
            ISSUE_BODY=$(echo "$ISSUE_DATA" | jq -r .body)

            CONTEXT_DETAILS_XML="<details><title>$ISSUE_TITLE</title><body>$ISSUE_BODY</body></details>"
            # DIFF_XML remains empty for issues
            PROMPT_INSTRUCTION="Based *only* on the information provided within the <github_context> XML structure (including issue details and comments), please provide a response to the <user_request>."
            echo "Issue details fetched."
          fi

          # --- Assemble Final Prompt ---
          # Removed || true - script will fail here if there's an issue
          # Use process substitution potentially or just ensure vars are clean. Direct heredoc should be fine.
          read -r -d '' FORMATTED_PROMPT <<EOF
          <github_context type="$CONTEXT_TYPE" number="$ISSUE_OR_PR_NUMBER">
          $CONTEXT_DETAILS_XML
          $DIFF_XML
            <comments>
          $COMMENTS_XML
            </comments>
            <user_request>
          $USER_REQUEST_BODY
            </user_request>
          </github_context>

          $PROMPT_INSTRUCTION
          EOF

          echo "Final prompt assembled."
          # Output the potentially large prompt securely using delimiters
          echo "formatted_prompt<<EOF_PROMPT_MARKER" >> $GITHUB_OUTPUT
          echo "$FORMATTED_PROMPT" >> $GITHUB_OUTPUT
          echo "EOF_PROMPT_MARKER" >> $GITHUB_OUTPUT

      - name: Determine probe-chat Command
        id: determine_command
        run: |
          CMD="${{ secrets.PROBE_CHAT_COMMAND }}"
          if [[ -z "$CMD" ]]; then
            CMD="${{ inputs.default_probe_chat_command }}"
            echo "Using default probe-chat command."
          else
            echo "Using probe-chat command from PROBE_CHAT_COMMAND secret."
          fi
          echo "Final command: $CMD"
          echo "command=$CMD" >> $GITHUB_OUTPUT

      - name: Run probe-chat
        id: probe
        # Use bash for pipefail and better error handling
        shell: bash
        run: |
          # Exit script if any command fails, and ensure pipeline failures are caught
          set -e
          set -o pipefail

          PROMPT='${{ steps.format.outputs.formatted_prompt }}'
          COMMAND_TO_RUN='${{ steps.determine_command.outputs.command }}'
          RESPONSE_FILE="response.txt"
          ERROR_LOG="error.log"

          # Initialize files
          > "$RESPONSE_FILE"
          > "$ERROR_LOG"

          echo "Running probe-chat..."
          echo "--- Start AI Prompt (first 500 chars) ---"
          echo "${PROMPT:0:500}..." # Log only beginning of potentially large prompt
          echo "--- End AI Prompt Snippet ---"
          echo "Command to run: $COMMAND_TO_RUN"

          # Execute the command, capture stdout and stderr
          # Use a subshell to capture exit code without `set -e` terminating the whole script here
          EXIT_CODE=0
          echo "$PROMPT" | $COMMAND_TO_RUN > "$RESPONSE_FILE" 2> "$ERROR_LOG" || EXIT_CODE=$?

          if [ $EXIT_CODE -ne 0 ]; then
            echo "Error: probe-chat command failed with exit code $EXIT_CODE." >&2 # Log to Actions stderr
            echo "Stderr output from probe-chat:" >&2
            cat "$ERROR_LOG" >&2
            # Prepare error message for the comment output file
            echo "🤖 Error: AI command failed (exit code $EXIT_CODE)." > "$RESPONSE_FILE"
            echo "**Stderr:**" >> "$RESPONSE_FILE"
            echo '```' >> "$RESPONSE_FILE"
            cat "$ERROR_LOG" >> "$RESPONSE_FILE" || echo "(no stderr output captured)" >> "$RESPONSE_FILE"
            echo '```' >> "$RESPONSE_FILE"
            echo "Check the Action logs for the full prompt and details." >> "$RESPONSE_FILE"
            # *** Crucially: Make this specific step fail ***
            exit 1
          else
            echo "probe-chat command finished successfully."
          fi

      - name: Read Response or Error
        # This step runs ONLY if the 'probe' step succeeded OR if formatting failed earlier (job fails)
        # If 'probe' failed, the job fails at that step, and this step won't run.
        # We need this step to run even if 'probe' failed to capture the error message written to response.txt
        # Use `if: always()` to ensure it runs even if 'probe' fails
        if: always()
        id: read_response
        run: |
          RESPONSE=$(cat response.txt 2>/dev/null || echo "") # Read response or error, default to empty if file missing

          # Check if RESPONSE is empty or contains only whitespace, provide default
          # This covers cases where format failed before probe ran, or probe succeeded with no output
          if [[ -z "${RESPONSE// }" ]]; then
            # Check if the probe step actually failed to provide a more specific default
            if [[ "${{ steps.probe.outcome }}" == "failure" ]]; then
               RESPONSE="🤖 Processing failed: AI command execution error. Check Action logs."
            elif [[ "${{ steps.format.outcome }}" == "failure" ]]; then
               RESPONSE="🤖 Processing failed: Error during context preparation. Check Action logs."
            else
               RESPONSE="🤖 Processing finished, but no response was generated."
            fi
          fi
          echo "Response content captured."
          # Use EOF markers for multiline output
          echo "response<<EOF_RESPONSE_MARKER" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF_RESPONSE_MARKER" >> $GITHUB_OUTPUT


  # Job 2: Post the response back to GitHub
  post_response:
    # Run this job if the process_comment job was triggered (not skipped)
    # It will post either the success response or the error message captured by read_response
    if: needs.process_comment.result != 'skipped'
    runs-on: ubuntu-latest
    needs: [process_comment] # Depend on the first job
    # Permissions are defined at the workflow level
    steps:
      - name: Post Response Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the token passed from the caller
          repository: ${{ github.repository }} # Explicitly provide repo context
          # Use the reliably set issue number output
          issue-number: ${{ needs.process_comment.outputs.issue_number }}
          # Use the response body, which contains success or error message
          body: ${{ needs.process_comment.outputs.response_body }}
